production:
  db_user: "user"
  db_pass: "pass"
  db_host: "host"
  
development:
  db_user: "postgres"
  db_pass: "123456789"
  db_host: "localhost"

test:
  db_user: "user"
  db_pass: "pass"
  db_host: "host"
