production:
  db_user: postgres
  db_pass: '123456789'
  db_host: 'localhost'

development:
  db_user: postgres
  db_pass: '123456789'
  db_host: 'localhost'

test:
  db_user: postgres
  db_pass: '123456789'
  db_host: 'localhost'
