production:
  db_user: "postgres"
  db_pass: "123456789"
  db_host: "host"

development:
  db_user: "postgres"
  db_pass: "mila#1324"
  db_host: "localhost"

test:
  db_user: "postgres"
  db_pass: "123456789"
  db_host: "localhost"
