production:
  db_user: "postgres"
  db_pass: "mila1324"
  db_host: "host"

development:
  db_user: "postgres"
  db_pass: "mila1324"
  db_host: "host"

test:
  db_user: "postgres"
  db_pass: "mila1324"
  db_host: "host"
