default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432

development:
  <<: *default
  database: "codhab_production"
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host: <%= ENV['HOST'] %>


production:
  <<: *default
  database: codhab_development
  username: "<%= ENV['USERNAME'] %>"
  password: "<%= ENV['PASSWORD'] %>"
  host: "<%= ENV['HOST'] %>"


test:
  <<: *default
  database: codhab_test
  username: "<%= ENV['USERNAME'] %>"
  password: "<%= ENV['PASSWORD'] %>"
  host: "<%= ENV['HOST'] %>"

