default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432

development:
  <<: *default
  database: "codhab_development"
  username: "username"
  password: "password"
  host: "host"


production:
  <<: *default
  database: codhab_production
  username: "username"
  password: "password"
  host: "host"

test:
  <<: *default
  database: codhab_test
  username: "username"
  password: "password"
  host: "host"
