default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432

production:
  <<: *default
  database: codhab_production2
  username: <%= ENV["DB_PRODUCTION_USERNAME"] %>
  password: <%= ENV["DB_PRODUCTION_PASSWORD"] %>
  host: <%= ENV["DB_PRODUCTION_HOST"] %>
